config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/show'
  get 'products/index'
  get 'products/show'

  get '/contact', to: 'pages#contact'
  get '/about', to: 'pages#about'
  get '/products/sale', to: 'products#sale'
  get '/products/new', to: 'products#new'

  resources :cart, only: %i[create destroy ]




  get "home/index"
  root "home#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :customers
  resources :products do
    collection do
      get 'search'
    end
  end
  resources :categories

   # /checkout/create something
   scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/models/cucstomer.rb
class Cucstomer < ApplicationRecord
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 10
  belongs_to :category

  validates :name, presence: true
  validates :price, presence: true

  has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :initialize_session
  helper_method :cart

  def initialize_session
    session[:shopping_cart] ||= [] # empty array representind product id's
  end

  def cart
    Product.find(session[:shopping_cart])
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def create
    logger.debug("Adding #{params[:id]} to cart.")
    id = params[:id].to_i
    # session[:shopping_cart] << id # pushes id onto the end of the array
    product = Product.find(id)

    if session[:shopping_cart].include?(id) # pushes id onto the end of the array
      flash[:notice] = "✚ #{product.name} is already in the cart."
    elsif session[:shopping_cart] << id
      flash[:notice] = "✚ #{product.name} added to cart."
    end

    redirect_to cart_index_path
  end

  def destroy
    id = params[:id].to_i
    session[:shopping_cart].delete(id)
    product = Product.find(id)
    flash[:notice] = "➖ #{product.name} removed from cart."
    redirect_to cart_index_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    # establish a connection to Stripe and then redirect the user to the payment screen
    # product = Product.find(params[:product_id])

    # if product.nil?
    #   redirect_to root_path
    #   return
    # end

    # @session = Stripe::Checkout::Session.create(
    #   payment_method_types: ["card"],
    #   success_url:          "#{checkout_success_url}?session_id={CHECKOUT_SESSION_ID}",
    #   cancel_url:           checkout_cancel_url,
    #   line_items:           [
    #     name:        product.name,
    #     description: product.brand,
    #     amount:      product.price, # price * 100.to_i
    #     currency:    "cad",
    #     quantity:    1
    #   ]
    # )
    # respond_to do | format |
    # format.js #app/views/checkout/create.js.erb
    # end
    redirect_to @session.url, allow_other_host: true
  end

  def success
    # we took the customer's money
    @session = Stripe::Checkout::Session.retrieve(params[:session_id])
    @payment_intent = Stripe::PaymentIntent.retrieve(@session.payment_intent)
  end

  def cancel
    # something went wrong with payment!
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
    @page = Page.find_by(title: "Contact")
  end

  def about
    @page = Page.find_by(title: "About")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    # session[:visit_count] ||= 0
    # session[:visit_count] += 1
    # @visit_count = session[:visit_count]
    @product = Product.find(params[:id])
    @category = @product.category
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    category_search = "%#{params[:category]}%"
    @products = Product.where("name LIKE ?", wildcard_search).where("category_id LIKE ?",
                                                                    category_search)
  end

  def sale
    @products = Product.where.not(sale_price: nil).where("sale_price < price")
  end

  def new
    @products = Product.where("created_at >= ?", 3.days.ago)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def breadcrumbs(controller, action)
    crumbs = []
    product = @product
    category = @category
    if controller == "products" && action == "index"
      crumbs << link_to("Home", root_path)
    elsif controller == "products" && action == "show"
      crumbs << link_to("Home", root_path)
      crumbs << link_to("Products", products_path)
      crumbs << link_to(product.category.name, category_path(product.category))
      crumbs << product.name
    elsif controller == "categories" && action == "show"
      crumbs << link_to("Home", root_path)
      crumbs << link_to("Categories", categories_path)
      crumbs << category.name
    end
    crumb_str = ""
    crumbs.each_with_index do |crumb, i|
      crumb_str += if i == crumbs.length - 1
                     "<span class='active'>#{crumb}</span>"
                   else
                     "#{crumb} &raquo; "
                   end
    end
    crumb_str.html_safe
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/index.html.erb
<%= puts quantity%>

app/views/categories/index.html.erb
<% @categories.each do |c|%>
<li><%= link_to c.name, c %></li>
<%end%>

app/views/categories/show.html.erb
<div class="container" style="margin:auto">
<% @category.products.each do |product| %>
<%= render product%>
<%end%>
</div>

app/views/checkout/cancel.html.erb
<h1>
  Something went wrong!
</h1>

app/views/checkout/create.js.erb
const stripe = Stripe('<%= Rails.configuration.stripe[:publishable_key] %>');

stripe.redirectToCheckout({
  sessionId: '<%= @session.id %>'
}).then(function(result){
  console.log(result.error.message);
})

app/views/checkout/success.html.erb
<h1>
  Yay! we have you money 💰
  <%= debug @session %>
  <%= debug @payment_intent %>
</h1>

app/views/home/index.html.erb
<figure class="image" >
  <%= image_tag 'skinn.jpeg' , alt: "skincare",
  style: 'max-height: 32rem;'
  %>
</figure>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma-rtl.min.css">

     <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
   <section class= "container is-responsive">
<%= render partial:'shared/header'%>
<nav class="breadcrumb" style= "display: flex">
    <%= breadcrumbs(params[:controller], params[:action]) %>
  </nav>

<nav class="navbar-end" id="cart_nav">


          <%= link_to "Cart", cart_index_path%>
          <sup><%= cart.size %></sup>

            <% if cart.present? %>


              <ul>
                <% cart.each do |p| %>
                  <li>

  <%= hidden_field_tag :id, p.id %>
  <%= number_field_tag :quantity, session[:shopping_cart][p.id], min: 1 %>
  <%= submit_tag "Update Quantity" %>

                    <%= p.name %> <%= button_to '−', cart_path(p), method: :delete %>
                  </li>
                <% end %>
              </ul>
            <% end %>

      </nav>





<% if flash[:notice] %>
        <p>
          <%= flash[:notice] %>
        </p>
      <% end %>


    <%= yield %>
    </section>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<%= @page.body %>

app/views/pages/contact.html.erb
<h1>Contact Us</h1>
<%= @page.body %>

app/views/products/_product.html.erb
<div class="card m-5 " style="width:21%;float:left;height:400px">
<%if product.image.present? %>
  <div class="card-image">
    <figure class="image is-5by3">
      <%= image_tag url_for(product.image) , alt: product.name%>
    </figure>
  </div>
  <%end%>
  <div class="card-content">

  <p class="title" style="font-size:15px"><%= link_to product.name, product %></p>
   <p class="description">Brand: <%= product.brand %></p>
   <% if product.sale_price.present? %>
    <p class="subtitle" style="font-size:15px">Price: <strike><%= number_to_currency(product.price) %></strike> <span style="color:red"><%= product.sale_price %></span></p>

        <% else%>
         <p class="subtitle " style="font-size:15px">Price: <%= number_to_currency(product.price) %></p>
  <%end%>

<% if cart.include?(product)%>
    <%= button_to cart_path(product), method: :delete do %>
      ➖ Remove from cart
      <% end %>
<%else%>
    <%= form_with url: cart_index_path, method: :post do %>
        <%= hidden_field_tag(:id, product.id) %>
        <%= button_tag '➕ Add to Cart', class: "p-2"%>
      <% end %>
<%end%>

 <%= form_with url: checkout_create_path, remote: true do %>
      <% hidden_field_tag(:product_id, product.id) %>
      <% button_tag 'Buy Now 💳' ,class: "mt-2"%>
    <% end %>


  </div>
</div>

app/views/products/index.html.erb
<div class="container" style="margin:auto">
<% @products.each do |product| %>
<%= render product%>
<%end%>
</div>

app/views/products/new.html.erb
<div class="container" style="margin:auto">
<% @products.each do |product| %>
<div class="card m-5 " style="width:29%;float:left">
<%if product.image.present? %>
  <div class="card-image">
    <figure class="image is-4by3">
      <%= image_tag product.image %>
    </figure>
  </div>
  <%end%>
  <div class="card-content">

  <p class="title "><%= link_to product.name, product %></p>
        <p class="subtitle ">Price: <%= product.price %></p>
        <p class="subtitle ">Launched on: <%= product.created_at.strftime("%F") %></p>

  </div>
</div>
<%end%>
</div>

app/views/products/sale.html.erb
<div class="container" style="margin:auto">
<% @products.each do |product| %>
<%= render product%>
<%end%>
</div>

app/views/products/search.html.erb
<% if(@products.count == 0)%>
<p style="font-size:3rem; color:red">
No Products found while searching for: <%= params[:keywords]%>
</p>
<%else%>
<p>
Products found while searching for: <%= params[:keywords]%>
</p>
<ul>
<% @products.each do |product|%>
<li><%= link_to product.name, product %></li>
<%end%>
</ul>
<%end%>

app/views/products/show.html.erb
<%= render @product%>

app/views/shared/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">

  <div class="navbar-brand">
    <a class="navbar-item" href="#">
    <b>SKINESSENTIALS</b>
    </a>

  </div>

  <div id="navbarBasicExample" class="navbar-menu ">
    <div class="navbar-start">

      <div class="navbar-item"><%= link_to 'Home', root_path %></div>


 <div class="navbar-item has-dropdown is-hoverable">
        <div class="navbar-link">
         <%= link_to 'Our Products', products_index_path %>
        </div>




        <div class="navbar-dropdown">
         <% categories = Category.all %>
         <% categories.each do |c| %>
            <div class="navbar-item p-2">
            <%= link_to c.name, c %>
          </div>

        <%end%>

        </div>
      </div>
    </div>

      </div>

      <div class="navbar-item"><%= link_to 'Sale', products_sale_path%>
      <div class="navbar-item"><%= link_to 'New', products_new_path%>
      <div class="navbar-item"><%= link_to 'About Us', about_path %>
      </div>

      <div class="navbar-item"><%= link_to 'Contact Us', contact_path %></div>


      </div>

<div>
        <%= form_with(url: search_products_path, method: :get, local: true) do%>
        <div>
          <nav class="navbar filed is-grouped mt-3">
            <%= text_field_tag(:keywords,nil,class: "input", placeholder: "Search for products")%>
             <%= select_tag :category, options_for_select(Category.all.map{ |c| [c.name, c.id] }, params[:category]), prompt: "All categories" %>

            <%= submit_tag("search", class: "ml-3 button is-dark")%>
          </nav>
        </div>
        <%end%>
      </div>

  </div>
</nav>